

require(tidyr)
require(dplyr)
require(lhs)
require(ggsci)
require(hablar)
require(stringr)
library(lhs)
library(rrapply)
require(ggh4x)
source("datafunctions.R")
source("mortality.R")
source("demography.R")
source("diseases.R")
source("variables.R")
source("modelfunctions.R")
#source("plotfunctions.R")